CUDA_VISIBLE_DEVICES=0 python SAFT/main.py \
    --mode "test" \
    --data_path "edge_data/movie" \
    --load_ckpt_name "edge_data/movie/ckpt-gpu0/SAFT_GNN_small-True-0.001-64-best.pt" \
    --large False \
    --data_path "edge_data/movie" \
    --model_type "SAFT_GNN_small" \
    --epochs 300 \
    --early_stop 30 \
    --lr 1e-3 \
    --weight_decay 1e-2 \
    --adam_epsilon 1e-6 \
    --rd 107 \
    --prop_layers 1 \
    --tlambda 0 \
    --delta 0 \
    --pe_dim 16 \
    --model_name_or_path "prajjwal1/bert-tiny"
