CUDA_VISIBLE_DEVICES=0 python SAFT/main.py \
    --large False \
    --data_path "edge_data/movie" \
    --model_type "SAFT_GAU_small" \
    --epochs 300 \
    --early_stop 30 \
    --lr 1e-3 \
    --weight_decay 1e-2 \
    --adam_epsilon 1e-6 \
    --rd 107 \
    --prop_layers 5 \
    --tlambda 1.5 \
    --delta 1.5 \
    --pe_dim 32 \
    --model_name_or_path "prajjwal1/bert-tiny"
